project:
  type: book

book:
  title: "EPONYMOUS DICTIONARY OF TUMORS"
  subtitle: "v. 1.0"
  author: "Nikolai Danilov, MD, MPH"
  place: "Haifa, Israel"
  date: "2026"
  search: true
  chapters:
    - copyright.qmd  # Copyright info page. 
    - index.qmd     # Preface.
    - EpoDicTum_body.qmd     # The Dictionary itself (the A-Z chapters).
    - personalia.qmd  # Index of Personalia.

format:
  html:
    number-sections: false
    toc: true
    toc-depth: 3
    page-navigation: true
    chunk-level: 3 # Tells Quarto to start a new page at every H3 header.
    css: styles.css
    lightbox: auto
  pdf:
    number-sections: false
    toc: true
    toc-depth: 3
    page-navigation: true
    include-in-header: preamble.tex
    css: styles.css
    papersize: a4
    fontsize: 12pt
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
    fig-align: center
    fig-width: 5
    fig-height: 5
    
  
